name       : openconnect
version    : '8.02'
release    : 7
source     :
    - git|https://github.com/openconnect/openconnect.git : v8.02
license    : LGPL-2.1-only
component  : network.base
summary    : Open client for Cisco AnyConnect VPN
description: |
    Open client for Cisco AnyConnect VPN
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(liblz4)
    - pkgconfig(libproxy-1.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(openssl)
    - pkgconfig(p11-kit-1)
    - pkgconfig(stoken)
    - vpnc
rundeps    :
    - vpnc
patterns   :
    - docs : /usr/share/doc
setup      : |
    %reconfigure --sbindir=/usr/bin
build      : |
    %make
install    : |
    %make_install
