name       : openconnect
version    : '7.08'
release    : 4
source     :
    - ftp://ftp.infradead.org/pub/openconnect/openconnect-7.08.tar.gz : 1c44ec1f37a6a025d1ca726b9555649417f1d31a46f747922b84099ace628a03
license    : GPL-2.0
component  : network.base
summary    : Open client for Cisco AnyConnect VPN
description: |
    Open client for Cisco AnyConnect VPN
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(p11-kit-1)
    - pkgconfig(openssl)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libproxy-1.0)
    - pkgconfig(stoken)  
    - vpnc
rundeps    :
    - vpnc
patterns   :
    - docs : /usr/share/doc
setup      : |
    %configure --sbindir=/usr/bin
build      : |
    %make
install    : |
    %make_install
