name       : openconnect
version    : '8.10'
release    : 10
source     :
    - https://gitlab.com/openconnect/openconnect/-/archive/v8.10/openconnect-v8.10.tar.gz : 6aec9a7d3b4a38dfa3d30adb9ee9227c1ac39becf184b272fc5adbadf858292e
license    : LGPL-2.1-only
component  : network.base
summary    : Open client for Cisco AnyConnect VPN
description: |
    Open client for Cisco AnyConnect VPN
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(liblz4)
    - pkgconfig(libproxy-1.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(openssl)
    - pkgconfig(p11-kit-1)
    - pkgconfig(stoken)
    - vpnc
rundeps    :
    - vpnc
setup      : |
    %reconfigure --sbindir=/usr/bin
build      : |
    %make
install    : |
    %make_install
