name       : openconnect
version    : '7.08'
release    : 5
source     :
    - https://github.com/openconnect/openconnect/archive/v7.08.tar.gz : 7ca971feb461d694441547bc297517cee6b413d03cdd67c9af92275aa8c79d1b
license    : GPL-2.0-or-later
component  : network.base
summary    : Open client for Cisco AnyConnect VPN
description: |
    Open client for Cisco AnyConnect VPN
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(p11-kit-1)
    - pkgconfig(openssl)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libproxy-1.0)
    - pkgconfig(stoken)
    - vpnc
rundeps    :
    - vpnc
patterns   :
    - docs : /usr/share/doc
setup      : |
    %reconfigure --sbindir=/usr/bin
build      : |
    %make
install    : |
    %make_install
